### ISSUE TITLE
how to change bth to btc wallet

### ISSUE THREAD

**Issue by jaxporon** [guardaco/guarda-android-wallets#10]
hi 
your app src is go good tnx
your defult wallet to  this source after the run  is BCH and i want to say one qustion 
how i can  set wollet to btc after run ? 
please help me

**Comment by Laraoj** [comment]
I know someone who can be of help by walking you through on how to go about this, he's a fund recover expert who once helped me with recovering some btc that I lost through bad investment, I know he's vast in the crypto world, you can reach out to him on cheng66@protonmail.ch and talking to him about this issue you've got, I'm sure he will be glad to help you out.

**Comment by guardawallet** [comment]
Hello!

You need to change build variant in Android Studio. 
It is bchDebug, you need btcDebug

![image](https://user-images.githubusercontent.com/30776726/62858435-fcc71300-bd02-11e9-92ec-a16535ecb08f.png)
