### ISSUE TITLE
Where is the implementation of z-transactions for ZEC?

### ISSUE THREAD

**Issue by RaitoBezarius** [guardaco/guarda-android-wallets#11]
Hi there, I'm trying to read the implementation you used in your mobile app for shielded transactions, I cannot find any file related to this, except the z-addresses details which are empty packages.

**Comment by guardawallet** [comment]
Hello!

It is in another brunch, choose `gh-zapling-main`
https://github.com/guardaco/guarda-android-wallets/tree/gh-zapling-main
