### ISSUE TITLE
Add Wallet Password

### ISSUE THREAD

**Issue by trymeouteh** [guardaco/guarda-android-wallets#27]
Please add an option to set a PIN or password which will be needed to unlock the app instead of using the wallet file password. The wallet file password will still be used to encrypt the wallet but the PIN or password will allow quicker to access the wallet when you use a long wallet file password.

I would like this for the mobile and desktop wallet.

**Comment by actioncoininc** [comment]
This option is already present in app.

**Comment by trymeouteh** [comment]
Where is this option? I cannot find it anywhere.

**Comment by actioncoininc** [comment]
Under menu >> options >> security code

![Screenshot_20200615-135637~2](https://user-images.githubusercontent.com/57165860/84705460-43cbf900-af10-11ea-9a20-07d648267ccd.png)

**Comment by trymeouteh** [comment]
I do not see this on Android or desktop.

**Comment by trymeouteh** [comment]
I see this option in the 2.0 version of Android however this changes the wallet file password. I am suggesting secondary password just for unlocking the wallet. I have a very long password for my wallet file password and would not like to keep the long password and have a shorter password for unlocking the app.
