### ISSUE TITLE
Cash Account Integration

### ISSUE THREAD

**Issue by monsterbitar** [guardaco/guarda-android-wallets#4]
I am currently working on a specification for on-chain aliases that look like this: James#577821; to help convey payment information in a more convenient manner, particulary in verbal contexts.

The specification has undergone reasonable peer-review so far (by wallet developers, token developers, coinbase engineeers) but more feedback is always welcome.

Here's a link to the draft spec: https://gitlab.com/cash-accounts/specification/blob/master/SPECIFICATION.md

**Comment by guardawallet** [comment]
hi @monsterbitar! 
Sorry, must've missed your message here. Will sure take a look at what you have sent and thanks for reaching out to us!

**Comment by monsterbitar** [comment]
There's a webpage on cashaccount.info to try the system now, and multiple lookup servers in the wild. Bitcoin Unlimited recently voted to get support code writting to support wallet lookups and to support using the naming system in the node wallet.

If there is any questions, I'd love to help out, just let me know.
