### ISSUE TITLE
Not working on iOS 

### ISSUE THREAD

**Issue by rickyspires** [guardaco/guarda-android-wallets#8]
Hi . I just installed your app on the latest iOS iPhone . When I login it goes straight to a white blank screen :(

**Comment by guardawallet** [comment]
hi @rickyspires!
Pardon, we have missed your message here. Are you sure you are referring to our open-source wallets and not the main iOS multi-currency application? Please let us know. If you are talking of Guarda iOS wallet, updating the application will help you solve this issue.
